authentik:
  secret_key: "PleaseGenerateA50CharKey"
  error_reporting:
    enabled: true
  postgresql:
    password: "ThisIsNotASecurePassword"  

ingress:
  ingressClassName: nginx
  annotations:
    cert-manager.io/cluster-issuer: homelab-ca-issuer  
  enabled: true
  hosts:
    - host: authentik.home.lab
      paths:
        - path: "/"
          pathType: Prefix
  tls:
  - hosts:
    - authentik.home.lab
    secretName: tls-authentik.home.lab

postgresql:
  enabled: true
  postgresqlPassword: "ThisIsNotASecurePassword"

redis:
  enabled: true
