apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  labels:
    {{- include "helm.labels" . | nindent 4 }}
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: authentik-secrets
  namespace: authentik
spec:
  encryptedData:
    SECRET_KEY: AgBmJcnbM1GbZphFdi+cPk699o/aczqXkCKsDx13FsUMtA/ECDC3ug/XLFKKuYWcmxNEUZvFSepKFYQYe6w/zyLPfZnm2AYrtbOA20epU/UOZav8z//PO+lmCzRgl6gxS7MFgEC/s/k1DqC1ph5LS2YppaLeAvkOvgTbJ9wuc3KFQ6m8EsBu/6raO4kfB4Tr1WycYFG+Sqm4eBjw53+8Uqh4Nm4Mv0+kHpTGLs5Y87PsjdSdFxBE5eQi62ktg0ooatW8iODjpMSpeahmcvZR4S+zFb/D3764YCVpq8UG1+tRNSq895Yby0IvvCcQ1HBoWgMF2tehiitSmDlCiXA8abtETw4I8Tm8SK0TWKg1DNVjW1rj/sl8prgOhWLPAq6cnn6pmjJhVOjEg7pIn1Fh5xgqXsTCBI9+9JuX84M8+GVCjnViwGsmpgxjVxBR3vg7eX3z2o5YxBhpr7yFCOKS1hX5PXdvALFshIwF6gELAKdt1K5wKS52roeVOIZofSokfnA3zPMhVUeAqtR27nazJg6s4bPTioJIW+UTzl2RmTfMI865BnQz1YcrXQH76Hxf+rRi6jTF4Od1lL1XSveEHb+ACKFQUuavTesg1jgKkWkTuWaBw323M3iZa2f6hdyGrdgPN5PVcGPrSR8g4yYHTSscFnLr4yeCaI4qOoIMvHkIVGIRuHkncX2+HEHRJF/I5rbtS0tih+i7M38//dTsKnsRy6V0pNhwe/TEsuyme1OeQ6DOa6w=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: authentik-secrets
      namespace: authentik
    type: Opaque

# Replace sealed secret above with a normal secret
# 
# apiVersion: v1
# kind: Secret
# metadata:
#   name: authentik-secrets
# type: Opaque
# stringData:
#   SECRET_KEY: "YOUR_SUPER_SECRET_KEY"

